# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /var/lib/snapd/snap/clion/81/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /var/lib/snapd/snap/clion/81/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yaara/CLionProjects/benchmark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yaara/CLionProjects/benchmark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/var/lib/snapd/snap/clion/81/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/var/lib/snapd/snap/clion/81/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaara/CLionProjects/benchmark/CMakeFiles /home/yaara/CLionProjects/benchmark/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yaara/CLionProjects/benchmark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named benchClient

# Build rule for target.
benchClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchClient
.PHONY : benchClient

# fast build rule for target.
benchClient/fast:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/build
.PHONY : benchClient/fast

#=============================================================================
# Target rules for targets named benchServer

# Build rule for target.
benchServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchServer
.PHONY : benchServer

# fast build rule for target.
benchServer/fast:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/build
.PHONY : benchServer/fast

AbstractClient.o: AbstractClient.cpp.o

.PHONY : AbstractClient.o

# target to build an object file
AbstractClient.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/AbstractClient.cpp.o
.PHONY : AbstractClient.cpp.o

AbstractClient.i: AbstractClient.cpp.i

.PHONY : AbstractClient.i

# target to preprocess a source file
AbstractClient.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/AbstractClient.cpp.i
.PHONY : AbstractClient.cpp.i

AbstractClient.s: AbstractClient.cpp.s

.PHONY : AbstractClient.s

# target to generate assembly for a file
AbstractClient.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/AbstractClient.cpp.s
.PHONY : AbstractClient.cpp.s

AbstractServer.o: AbstractServer.cpp.o

.PHONY : AbstractServer.o

# target to build an object file
AbstractServer.cpp.o:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/AbstractServer.cpp.o
.PHONY : AbstractServer.cpp.o

AbstractServer.i: AbstractServer.cpp.i

.PHONY : AbstractServer.i

# target to preprocess a source file
AbstractServer.cpp.i:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/AbstractServer.cpp.i
.PHONY : AbstractServer.cpp.i

AbstractServer.s: AbstractServer.cpp.s

.PHONY : AbstractServer.s

# target to generate assembly for a file
AbstractServer.cpp.s:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/AbstractServer.cpp.s
.PHONY : AbstractServer.cpp.s

MainClient.o: MainClient.cpp.o

.PHONY : MainClient.o

# target to build an object file
MainClient.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/MainClient.cpp.o
.PHONY : MainClient.cpp.o

MainClient.i: MainClient.cpp.i

.PHONY : MainClient.i

# target to preprocess a source file
MainClient.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/MainClient.cpp.i
.PHONY : MainClient.cpp.i

MainClient.s: MainClient.cpp.s

.PHONY : MainClient.s

# target to generate assembly for a file
MainClient.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/MainClient.cpp.s
.PHONY : MainClient.cpp.s

MainServer.o: MainServer.cpp.o

.PHONY : MainServer.o

# target to build an object file
MainServer.cpp.o:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/MainServer.cpp.o
.PHONY : MainServer.cpp.o

MainServer.i: MainServer.cpp.i

.PHONY : MainServer.i

# target to preprocess a source file
MainServer.cpp.i:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/MainServer.cpp.i
.PHONY : MainServer.cpp.i

MainServer.s: MainServer.cpp.s

.PHONY : MainServer.s

# target to generate assembly for a file
MainServer.cpp.s:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/MainServer.cpp.s
.PHONY : MainServer.cpp.s

Massage.o: Massage.cpp.o

.PHONY : Massage.o

# target to build an object file
Massage.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/Massage.cpp.o
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/Massage.cpp.o
.PHONY : Massage.cpp.o

Massage.i: Massage.cpp.i

.PHONY : Massage.i

# target to preprocess a source file
Massage.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/Massage.cpp.i
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/Massage.cpp.i
.PHONY : Massage.cpp.i

Massage.s: Massage.cpp.s

.PHONY : Massage.s

# target to generate assembly for a file
Massage.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/Massage.cpp.s
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/Massage.cpp.s
.PHONY : Massage.cpp.s

asioClient.o: asioClient.cpp.o

.PHONY : asioClient.o

# target to build an object file
asioClient.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/asioClient.cpp.o
.PHONY : asioClient.cpp.o

asioClient.i: asioClient.cpp.i

.PHONY : asioClient.i

# target to preprocess a source file
asioClient.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/asioClient.cpp.i
.PHONY : asioClient.cpp.i

asioClient.s: asioClient.cpp.s

.PHONY : asioClient.s

# target to generate assembly for a file
asioClient.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/asioClient.cpp.s
.PHONY : asioClient.cpp.s

asioServer.o: asioServer.cpp.o

.PHONY : asioServer.o

# target to build an object file
asioServer.cpp.o:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/asioServer.cpp.o
.PHONY : asioServer.cpp.o

asioServer.i: asioServer.cpp.i

.PHONY : asioServer.i

# target to preprocess a source file
asioServer.cpp.i:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/asioServer.cpp.i
.PHONY : asioServer.cpp.i

asioServer.s: asioServer.cpp.s

.PHONY : asioServer.s

# target to generate assembly for a file
asioServer.cpp.s:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/asioServer.cpp.s
.PHONY : asioServer.cpp.s

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/client.cpp.s
.PHONY : client.cpp.s

clientFactory.o: clientFactory.cpp.o

.PHONY : clientFactory.o

# target to build an object file
clientFactory.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/clientFactory.cpp.o
.PHONY : clientFactory.cpp.o

clientFactory.i: clientFactory.cpp.i

.PHONY : clientFactory.i

# target to preprocess a source file
clientFactory.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/clientFactory.cpp.i
.PHONY : clientFactory.cpp.i

clientFactory.s: clientFactory.cpp.s

.PHONY : clientFactory.s

# target to generate assembly for a file
clientFactory.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/clientFactory.cpp.s
.PHONY : clientFactory.cpp.s

libuvCLient.o: libuvCLient.cpp.o

.PHONY : libuvCLient.o

# target to build an object file
libuvCLient.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/libuvCLient.cpp.o
.PHONY : libuvCLient.cpp.o

libuvCLient.i: libuvCLient.cpp.i

.PHONY : libuvCLient.i

# target to preprocess a source file
libuvCLient.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/libuvCLient.cpp.i
.PHONY : libuvCLient.cpp.i

libuvCLient.s: libuvCLient.cpp.s

.PHONY : libuvCLient.s

# target to generate assembly for a file
libuvCLient.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/libuvCLient.cpp.s
.PHONY : libuvCLient.cpp.s

libuvServer.o: libuvServer.cpp.o

.PHONY : libuvServer.o

# target to build an object file
libuvServer.cpp.o:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/libuvServer.cpp.o
.PHONY : libuvServer.cpp.o

libuvServer.i: libuvServer.cpp.i

.PHONY : libuvServer.i

# target to preprocess a source file
libuvServer.cpp.i:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/libuvServer.cpp.i
.PHONY : libuvServer.cpp.i

libuvServer.s: libuvServer.cpp.s

.PHONY : libuvServer.s

# target to generate assembly for a file
libuvServer.cpp.s:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/libuvServer.cpp.s
.PHONY : libuvServer.cpp.s

rpcClient.o: rpcClient.cpp.o

.PHONY : rpcClient.o

# target to build an object file
rpcClient.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/rpcClient.cpp.o
.PHONY : rpcClient.cpp.o

rpcClient.i: rpcClient.cpp.i

.PHONY : rpcClient.i

# target to preprocess a source file
rpcClient.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/rpcClient.cpp.i
.PHONY : rpcClient.cpp.i

rpcClient.s: rpcClient.cpp.s

.PHONY : rpcClient.s

# target to generate assembly for a file
rpcClient.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/rpcClient.cpp.s
.PHONY : rpcClient.cpp.s

rpcServer.o: rpcServer.cpp.o

.PHONY : rpcServer.o

# target to build an object file
rpcServer.cpp.o:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/rpcServer.cpp.o
.PHONY : rpcServer.cpp.o

rpcServer.i: rpcServer.cpp.i

.PHONY : rpcServer.i

# target to preprocess a source file
rpcServer.cpp.i:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/rpcServer.cpp.i
.PHONY : rpcServer.cpp.i

rpcServer.s: rpcServer.cpp.s

.PHONY : rpcServer.s

# target to generate assembly for a file
rpcServer.cpp.s:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/rpcServer.cpp.s
.PHONY : rpcServer.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/server.cpp.s
.PHONY : server.cpp.s

serverFactory.o: serverFactory.cpp.o

.PHONY : serverFactory.o

# target to build an object file
serverFactory.cpp.o:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/serverFactory.cpp.o
.PHONY : serverFactory.cpp.o

serverFactory.i: serverFactory.cpp.i

.PHONY : serverFactory.i

# target to preprocess a source file
serverFactory.cpp.i:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/serverFactory.cpp.i
.PHONY : serverFactory.cpp.i

serverFactory.s: serverFactory.cpp.s

.PHONY : serverFactory.s

# target to generate assembly for a file
serverFactory.cpp.s:
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/serverFactory.cpp.s
.PHONY : serverFactory.cpp.s

session.o: session.cpp.o

.PHONY : session.o

# target to build an object file
session.cpp.o:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/session.cpp.o
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/session.cpp.o
.PHONY : session.cpp.o

session.i: session.cpp.i

.PHONY : session.i

# target to preprocess a source file
session.cpp.i:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/session.cpp.i
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/session.cpp.i
.PHONY : session.cpp.i

session.s: session.cpp.s

.PHONY : session.s

# target to generate assembly for a file
session.cpp.s:
	$(MAKE) -f CMakeFiles/benchClient.dir/build.make CMakeFiles/benchClient.dir/session.cpp.s
	$(MAKE) -f CMakeFiles/benchServer.dir/build.make CMakeFiles/benchServer.dir/session.cpp.s
.PHONY : session.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... benchClient"
	@echo "... benchServer"
	@echo "... AbstractClient.o"
	@echo "... AbstractClient.i"
	@echo "... AbstractClient.s"
	@echo "... AbstractServer.o"
	@echo "... AbstractServer.i"
	@echo "... AbstractServer.s"
	@echo "... MainClient.o"
	@echo "... MainClient.i"
	@echo "... MainClient.s"
	@echo "... MainServer.o"
	@echo "... MainServer.i"
	@echo "... MainServer.s"
	@echo "... Massage.o"
	@echo "... Massage.i"
	@echo "... Massage.s"
	@echo "... asioClient.o"
	@echo "... asioClient.i"
	@echo "... asioClient.s"
	@echo "... asioServer.o"
	@echo "... asioServer.i"
	@echo "... asioServer.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... clientFactory.o"
	@echo "... clientFactory.i"
	@echo "... clientFactory.s"
	@echo "... libuvCLient.o"
	@echo "... libuvCLient.i"
	@echo "... libuvCLient.s"
	@echo "... libuvServer.o"
	@echo "... libuvServer.i"
	@echo "... libuvServer.s"
	@echo "... rpcClient.o"
	@echo "... rpcClient.i"
	@echo "... rpcClient.s"
	@echo "... rpcServer.o"
	@echo "... rpcServer.i"
	@echo "... rpcServer.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... serverFactory.o"
	@echo "... serverFactory.i"
	@echo "... serverFactory.s"
	@echo "... session.o"
	@echo "... session.i"
	@echo "... session.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

